Anki/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flashcards/', include("flashcards.urls", namespace="flashcards")),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import *


# Create your views here.
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully!')
                else:
                    return HttpResponse('Disabled Account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "base.css" %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <span class="logo">Anki</span>
    {% if request.user.is_authenticated %}

  {% endif %}
  <span class="user">
    {% if request.user.is_authenticated %}
      Hello {{ request.user.first_name }},
      <a href="{% url 'account:logout' %}">Logout</a>
    {% else %}
      <a href="{% url "account:login" %}">Log-in</a>
    {% endif %}
  </span>
  </div>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>