Anki/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flashcards/', include("flashcards.urls", namespace="flashcards")),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

flashcards/urls.py
from django.urls import path

from flashcards.views import *

app_name = 'flashcards'
urlpatterns = [
    path('', index, name='dashboard'),
    # path('<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('<int:card_id>', card_detailview, name='card_detail'),
    path('next/', nextcardview, name='next'),
    path("recite/<int:card_id>/<int:rank>", cardreciteview, name="recite"),
    path("recitedata/", recitedatadisplay, name="display"),
    path('search/', search, name='search'),
    path('undo/<int:card_id>', undo, name='undo'),
    path('undo_list/<int:list_id>/<int:progress>/', undo_list, name='undo_list'),
    path('websearch/', websearch, name='websearch'),
    path('dict/', dict_search, name='dict'),
    path('create_wordlist_by_diff/', create_wordlist_by_diff, name='create_wordlist_by_diff'),
    path('create_wordlist_by_tag/', create_wordlist_by_tag, name='create_wordlist_by_tag'),
    path('delete_wordlist/<int:wordlist_id>/', delete_wordlist, name='delete_wordlist'),
    path('recite_wordlist/<int:wordlist_id>/<int:progress>/<int:rank>/', recite_wordlist, name='recite_wordlist'),
    path('word_add_tags/<int:word_id>/<slug:tag>/<int:section>/', word_add_tags, name='word_add_tags'),
    path('word_delete_tags/<int:word_id>/<slug:tag>/<int:section>/', word_delete_tags, name='word_delete_tags'),
    path('word_edit/<int:word_id>/<int:section>/', word_edit, name='word_edit'),
    path('word_add/', word_add, name='word_add'),
    path('word_delete/<int:word_id>/', word_delete, name='word_delete'),
]

flashcards/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Card(models.Model):
    cid = models.PositiveIntegerField(unique=True, null=True)
    group = models.CharField(max_length=20)
    question = models.CharField(max_length=200, default="none", blank=False)
    answer = models.CharField(max_length=200, default="none", blank=False)
    example = models.CharField(max_length=200)
    translation = models.CharField(max_length=200)
    extra = models.CharField(max_length=200)
    tags = TaggableManager()

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('cid',)
        # verbose_name = 'category'
        # verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('flashcards:card_detail',
                       args=[self.id])


# 每次使用时的数据，作为外键与卡片绑定

class Recitedata(models.Model):
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    rank = models.PositiveIntegerField(verbose_name="easy or diff?", default=0)
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name="recitedata")

    def __str__(self):
        return str(self.date) + ":" + str(self.rank)

    class Meta:
        ordering = ('date',)


class WordList(models.Model):
    owner = models.ForeignKey(User, models.CASCADE, related_name='owner')
    name = models.CharField(max_length=20, blank=False)
    wordlist = models.CharField(max_length=20000, blank=False)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    progress = models.PositiveIntegerField(blank=False, default=0)
    len_list = models.PositiveIntegerField(blank=False, default=50)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('date',)

flashcards/forms.py
from django import forms
from .models import Card


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CreateForm(forms.Form):
    query2 = forms.CharField()


class CardForm(forms.ModelForm):
    class Meta:
        Model = Card
        fields = ['group', 'question', 'answer', 'example', 'translation', 'extra']

flashcards/views.py
import json
import random
import collections
from django.utils import timezone
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from readmdict import MDX
from taggit.models import Tag

from .forms import *
from .models import *
from .web_query import find_synonym


class CardListView(ListView):
    model = Card
    template_name = 'flashcards/list.html'


class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = 'flashcards/back3.html'


# card_detail函数版
def card_detailview(request, card_id):
    # 获取card实例
    card = get_object_or_404(Card, id=card_id)
    return render(request,
                  'flashcards/back3.html',
                  {'object': card,
                   'tags': card.tags.all()})


# 背诵
@login_required
def cardreciteview(request, card_id, rank):
    # 获取card实例
    card = get_object_or_404(Card, id=card_id)

    # 创建并保存
    recitedata = Recitedata(rank=rank, card=card)
    recitedata.save()
    # 生成随机数并跳转至下一卡片
    card = Card.objects.filter(id=str(random.randrange(1, 7000, 1)))[0]
    return redirect(card.get_absolute_url())


# 下一张卡片
@login_required
def nextcardview(request):
    card = Card.objects.filter(id=str(random.randrange(1, 7000, 1)))[0]
    return redirect(card.get_absolute_url())


# 展示数据
@login_required
def recitedatadisplay(request):
    # 按rank排序，后续改进
    recitedata = Recitedata.objects.order_by("rank")
    # 使用set以防止card重复
    cards = set([data.card for data in recitedata])
    datas = [{'card': card, 'recitedata': card.recitedata.all()} for card in cards]
    return render(request,
                  'flashcards/recitedata.html',
                  {'datas': datas})


@login_required
def search(request):
    cards = []
    cd = {"query": ''}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['query'][0:2] == 'T:':
            tag = get_object_or_404(Tag, slug=cd['query'][2:])
            cards = Card.objects.filter(tags__in=[tag])
        else:
            cards = Card.objects.filter(
                Q(question__icontains=cd['query']) | Q(example__icontains=cd['query']))
            # 将搜索字段替换为红色
            for card in cards:
                card.question = card.question.replace(cd['query'], "<span id='red'><b>" + cd['query'] + "</b></span>")
                card.example = card.example.replace(cd['query'], "<span id='red'><b>" + cd['query'] + "</b></span>")

    if cd['query'] == '':
        form = SearchForm()

    return render(request, 'flashcards/search.html', {'cards': cards, 'searchvalue': cd['query'], 'form': form})


# 首页
@login_required
def index(request):
    cards = Card.objects.all()
    form = SearchForm()
    type_proportion = {
        'cihui': len(Card.objects.filter(group__startswith='词汇')),
        'duanyu': len(Card.objects.filter(group__startswith='短语')),
        'bianxi': len(Card.objects.filter(group__startswith='辨析'))
    }
    # 获取当前用户的单词列表
    wordlists = request.user.owner.all()
    # 获取过去七天的背诵数据
    now = timezone.now()
    start = now - timedelta(days=7, hours=now.hour, minutes=now.minute, seconds=now.second)
    recitedata = Recitedata.objects.filter(date__gt=start)
    rank_count_by_day = []
    for i in range(1, 8):
        all_data = recitedata.filter(date__gt=start + timedelta(days=i), date__lt=start + timedelta(days=i + 1))
        counter = collections.Counter([data.rank for data in all_data])
        rank_count_by_day.append([counter[1], counter[2], counter[3], counter[4]])
    rank_count_by_rank = []
    for i in range(0, 4):
        rank_count_by_rank.append([rank_day[i] for rank_day in rank_count_by_day])
    # 仅返回有单词的tag
    tags = filter(lambda tag: len(Card.objects.filter(tags__in=[tag])), Tag.objects.all())
    return render(request, 'flashcards/anki.html',
                  {'len': len(cards),
                   'type_proportion': type_proportion,
                   'lenlist': len(WordList.objects.all()),
                   'form': form,
                   'wordlists': wordlists,
                   'tags': tags,
                   'recitedata': rank_count_by_rank, },

                  )


# 删除背诵记录
@login_required
def undo(request, card_id):
    # 需要撤回的卡片和需要删除背诵记录的卡是一张卡
    card = Card.objects.filter(id=card_id)
    card[0].recitedata.latest('date').delete()

    return redirect(card[0].get_absolute_url())


# 删除背诵记录
@login_required
def undo_list(request, list_id, progress):
    wordlist = get_object_or_404(WordList, id=list_id)
    id_list = list(map(lambda dic: dic['id'], json.loads(wordlist.wordlist)))
    card_id = id_list[progress - 1]
    # 需要撤回到的卡片和需要删除背诵记录的卡是一张卡
    card = Card.objects.filter(id=card_id)
    card[0].recitedata.latest('date').delete()
    # 修改进度
    return redirect('flashcards:recite_wordlist', list_id, progress - 1, 0)


# 网络搜索
@login_required
def websearch(request):
    cd = {"query": ''}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
        words = find_synonym(cd['query'])
    else:
        form = SearchForm()
        words = []
    return render(request, 'flashcards/webquery.html',
                  {"words": words, 'searchvalue': cd['query'], 'form': form}, )


@login_required
def dict_search(request):
    cd = {"query": ''}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
        # # 获取词汇排名
        # # 加载mdx文件
        # filename = "flashcards/static/dict/COCA/COCA Frequency 60000.mdx"
        # headwords = [*MDX(filename)]  # 单词名列表
        # items = [*MDX(filename).items()]  # 释义html源码列表
        #
        # # 查词，返回单词和html文件
        #
        # queryWord = cd['query']
        #
        # # print(headwords[120:123])
        # html_result = ''
        # try:
        #     wordIndex = headwords.index(queryWord.encode())
        #     word, html = items[wordIndex]
        #     word, html_head = word.decode(), html.decode()
        # except ValueError:
        #     html_result = 'No Results!'
        # 加载mdx文件
        filename = "flashcards/static/dict/牛津/牛津高阶8简体.mdx"
        headwords = [*MDX(filename)]  # 单词名列表
        items = [*MDX(filename).items()]  # 释义html源码列表

        # 查词，返回单词和html文件

        queryWord = cd['query']

        # print(headwords[120:123])
        html_result = ''
        try:
            wordIndex = headwords.index(queryWord.encode())
            word, html = items[wordIndex]
            word, html_result = word.decode(), html.decode()
        except ValueError:
            # 首字母大写的问题
            try:
                wordIndex = headwords.index(queryWord.lower().encode())
                word, html = items[wordIndex]
                word, html_result = word.decode(), html.decode()
            except ValueError:
                html_result = 'No Results!'
    else:
        form = SearchForm()
        html_result = ''

    return render(request, 'flashcards/dict.html',
                  {'html_result': html_result, 'form': form, 'searchvalue': cd['query'],
                   },
                  )


@login_required
def create_wordlist_by_diff(request):
    cd = {"query": 'list'}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
    # 找到最近的三个复习data并累计，生成一个字典
    rank_sum_dict = map(lambda card: {'id': card.id, 'rank_sum': sum(
        sorted([Recitedata.rank for Recitedata in card.recitedata.order_by('-date')], reverse=True)[0:3])
    if len(card.recitedata.all()) > 2
    else sum([Recitedata.rank for Recitedata in card.recitedata.order_by('-date')])}
                        , Card.objects.all())
    # 按rank排序，取前五十个值
    # 不知道为什么id列表总为空
    # id_list = [dic['id'] for dic in sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]]
    # id_list = list(
    #     map(lambda dic: dic['id'], sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]))
    # print(id_list)
    sort_list = sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]
    wordlist = WordList(owner=request.user, name=cd['query'], wordlist=json.dumps(sort_list)
                        , len_list=len(sort_list))
    wordlist.save()
    messages.success(request, '单词列表创建成功')
    return redirect('flashcards:dashboard')


@login_required
def create_wordlist_by_tag(request):
    cd = {"query": 'list', "tag": 'marked'}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
    tag = get_object_or_404(Tag, slug=request.GET['tag'])
    cards = Card.objects.filter(tags__in=[tag])
    id_list = [{'id': card.id} for card in cards]
    wordlist = WordList(owner=request.user, name=cd['query'], wordlist=json.dumps(id_list)
                        , len_list=len(id_list))
    wordlist.save()
    messages.success(request, '单词列表创建成功')
    return redirect('flashcards:dashboard')


@login_required
def recite_wordlist(request, wordlist_id, progress, rank):
    wordlist = WordList.objects.filter(id=wordlist_id)[0]
    # 判断请求progress和数据库progress是否相等，若不同，则将后者覆盖（在重新复习的时候可能出现的问题）
    if progress == 0 and wordlist.progress != 0:
        wordlist.progress = progress

    # json解析单词列表id
    id_list = list(map(lambda dic: dic['id'], json.loads(wordlist.wordlist)))
    # 判断是刚进入还是进入后第一次提交卡片
    # 若提交，则更新进度
    # 若刚进入，则不更新进度

    if rank > 0:
        # 获取当前card实例

flashcards/templates/flashcards/anki.html
{% extends "flashcards/base.html" %}
{% load static %}
{% load flashcards_tags %}
{% block title %}Anki{% endblock %}
{% block head %}
<script src="https://cdn.jsdelivr.net/npm/echarts@5.2.2/dist/echarts.js"></script>
        <style>
        a{
            text-decoration: none;
        }
        #red{
            color: red;
        }
        #id_query{
        margin-top: 2%;}
    </style>
{% endblock %}
{% block Anki %} active{% endblock %}
{% block content %}
    {% if messages %}
    <div class="mt-1">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible" role="alert">
        {{ message|safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button></div>
    {% endfor %}
    </div>
    {% endif %}
    <h6 class="lead h6">Hello,{{ request.user }} <a href="{% url 'account:logout' %}">Logout</a></h6>
    <h6 class="lead h6">当前词库有{{ len }}个单词，{{ lenlist }}个单词列表
    <a class="btn btn-outline-primary btn-sm" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
  创建单词列表
</a>
    </h6>
<!--创建单词列表表单-->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">创建单词列表</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      <h6 class="lead h6">以难度创建</h6>
        <form  id = 'form1' class="align-items-center col-12 " method="get" action="{% url 'flashcards:create_wordlist_by_diff' %}">

        <div class="form-floating mb-3 mt-3">
        <input type="text" class="form-control" id="floatingInput" placeholder="list" name="query">
        <label for="floatingInput">列表名：</label>
        </div>

        {% csrf_token %}

        </form>
    </div>
    <div>
        <h6 class="lead h6">以标签创建</h6>
        <form  id = 'form2' class="align-items-center col-12 " method="get" action="{% url 'flashcards:create_wordlist_by_tag' %}">

    <div class="form-floating mb-3">

      <select class="form-select" id="tagfloatingSelect" aria-label="Floating label select example" name="tag">

          {% for tag in tags %}
              <option value="{{ tag }}" name="{{ tag }}">{{ tag }}</option>
          {% endfor %}

      </select>
      <label for="tagfloatingSelect">请选择标签</label>
    </div>
     <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingInput2" placeholder="list" name="query">
      <label for="floatingInput2">列表名：</label>
    </div>

{% csrf_token %}

</form>
    </div>
  </div>
</div>
<!--创建单词列表表单结束-->
    <div class="container-fluid">
<ol class="list-group list-group-numbered">
   {% for wordlist in wordlists %}
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto" >
        <div class="fw-bold"><a class='link' href="{% if wordlist.progress != wordlist.len_list %}{% url 'flashcards:recite_wordlist' wordlist.id wordlist.progress 0 %}{% else %}{% url 'flashcards:recite_wordlist' wordlist.id 0 0 %}{% endif %}">{{ wordlist.name }}</a>
        <span class="badge rounded-pill bg-primary">{{ wordlist.progress }}/{{ wordlist.len_list }}</span>
        <span class="badge rounded-pill bg-danger" onClick="location.href='{% url 'flashcards:delete_wordlist' wordlist.id %}'">Delete</span>
        </div>
    </div>

  </li>

    {% endfor %}
</ol>
    </div>



    <div class="container">

<div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12">
        <div id="main2" style="width: 100%;height:400px;" ></div>
    </div>
</div>

    </div>


{% endblock %}
{% block script %}

// 图表


var chartDom = document.getElementById('main2');
var myChart = echarts.init(chartDom);
var option;
var type = {"1":'Easy',"2":'Mid',"3":'Diff',"4":'Forget'};
option = {
    title: {
    left:'center',
    text: 'ReciteData',
    textStyle: {
      color: '#235894'
    }
  },
  angleAxis: {
    type: 'category',
    data: ['6 day', '5 day', '4 day', '3 day', '2 day', '1 day', 'Today']
  },
  radiusAxis: {},
  polar: {},
  series: [

    {% for data in recitedata %}
            {
      type: 'bar',
      data: {{ data }},
      coordinateSystem: 'polar',
      name: type['{{ forloop.counter }}'],
      stack: 'a',
      emphasis: {
        focus: 'series'
      }
    },
    {% endfor %}

  ],
  legend: {
    show: true,
    data: ['Easy', 'Mid', 'Diff','Forget'],
    top: 'bottom',
  }
};

option && myChart.setOption(option);
{% endblock %}

flashcards/templates/flashcards/back3.html
{% extends "flashcards/base.html" %}
{% load static %}
{% load flashcards_tags %}
{% block title %}Anki Card{% endblock %}

{% block head %}
    <style>
    .link{
        text-decoration: none;
        font-weight: bold;
        }
    .word.accordion-button::after{
    display: none;}
    #footer{
    position: fixed;
    bottom: 0;
    padding-bottom: 0;
    margin-bottom: 0;
    }
    #Anki{
        display: none;
    }
    </style>
{% endblock %}
{% block Recite %} active{% endblock %}
{% block navbar %}
    <!--添加编辑栏-->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="Edit" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Card
      </a>
      <ul class="dropdown-menu" aria-labelledby="Edit">
        <li><a class="dropdown-item" href="{% url 'flashcards:word_add_tags' object.id 'marked' 0 %}">Mark!</a></li>
        <li><a class="dropdown-item " href="#EditCard" data-bs-toggle="offcanvas" role="button" aria-controls="EditCard">Edit</a></li>
        <li><a class="dropdown-item" href="{% url 'flashcards:word_delete' object.id %}">Delete</a></li>
        <li><a class="dropdown-item" href="{% url 'flashcards:word_add' %}">Add Word</a></li>
      </ul>
    </li>
<!--编辑单词表单-->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="EditCard" aria-labelledby="EditCardLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="EditCardLabel">编辑单词</h5>

    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <form  id = 'form1' class="align-items-center col-12 " method="post" action="{% url 'flashcards:word_edit' object.id 0 %}">
    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput0" placeholder="" name="group" value="{{ object.group|safe }}">
    <label for="floatingInput0">group</label>
    </div>
    <div class="form-floating mb-3 mt-3">
    <input type="text" class="form-control" id="floatingInput1" placeholder="" name="question" value="{{ object.question|safe }}">
    <label for="floatingInput1">question</label>
    </div>
    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput2" placeholder="" name="answer" value="{{ object.answer|pureword|safe }}">
    <label for="floatingInput2">answer</label>
    </div>

    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput3" placeholder="" name="example" value="{{ object.example|safe }}">
    <label for="floatingInput3">example</label>
    </div>

    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput4" placeholder="" name="translation" value="{{ object.translation|safe }}">
    <label for="floatingInput4">translation</label>
    </div>

    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput5" placeholder="" name="extra" value="{{ object.extra|safe }}">
    <label for="floatingInput5">extra</label>
    </div>

    <div class="form-floating mb-3 mt-3">

    <input type="text" class="form-control" id="floatingInput6" placeholder="" name="tag">
    <label for="floatingInput6">Add Tag</label>
    </div>
    <button type="submit" class="btn btn-outline-primary">Submit!</button>

    {% csrf_token %}

    </form>
  </div></div>
{% endblock %}
{% block content %}
        {% if messages %}
    <div class="mt-1">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible" role="alert">
        {{ message|safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button></div>
    {% endfor %}
    </div>
    {% endif %}
        <!-- 卡片正面 -->
    <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingZero">
      <button class="accordion-button collapsed word" type="button" data-bs-toggle="collapse" aria-expanded="false">
        {{ object.group }}
        <div class="" style="position: fixed;right: 5%">
                                {% for tag in tags %}
              <span class="badge rounded-pill bg-primary position-relative">{{ tag }}
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" onClick="location.href='{% url 'flashcards:word_delete_tags' object.id tag 0%}'">
    X
  </span></span>
          {% endfor %}
        </div>
      </button>
    </h2>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="accordion-button collapsed "  type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne" onclick="play()">
          <a class="link" href='{% url 'flashcards:dict' %}?query={{ object.question |pureword |safe}}'>{{ object.question |pureword |safe}}</a>
      </button>

    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne">
      <div class="accordion-body">{{ object.answer |safe}}</div>
    </div>
  </div>
  <div class="accordion-item" id="example">
    <h2 class="accordion-header" id="flush-headingTwo">
      <button id="example_button" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          <div>{{ object.example |safe}}</div>
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" >
      <div class="accordion-body">{{ object.translation |safe}}</div>
    </div>
  </div>
  <div class="accordion-item" id="extra">
    <h2 class="accordion-header" id="flush-headingThree">
      <button  class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="true" aria-controls="flush-collapseThree">
        EXTRA
      </button>
    </h2>
    <div id="flush-collapseThree" class="accordion-collapse  open" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
      <div id="extra_button" class="accordion-body">{{ object.extra |safe}}</div>
    </div>
  </div>
</div>

    <!-- 音频 -->
    <audio autoplay id="audio" src={{object.question|pureword|youdao}}>ERROR</audio>
{% endblock %}

{% block footer %}
    <!-- 难易选项 -->
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
        <button type="button" class="btn btn-secondary" onClick=undo()>UNDO</button>
        <button type="button" class="btn btn-danger" onClick="location.href='{% url "flashcards:recite" object.id 4%}'">FORGET</button>
        <button type="button" class="btn btn-warning" onClick="location.href='{% url "flashcards:recite" object.id 3%}'">DIFF</button>
        <button type="button" class="btn btn-info" onClick="location.href='{% url "flashcards:recite" object.id 2%}'">MID</button>
        <button type="button" class="btn btn-success" onClick="location.href='{% url "flashcards:recite" object.id 1%}'">EASY</button>
    </div>
{% endblock %}

{% block script %}
    //处理例句和扩展为空
    var example=document.getElementById("example");
    var extra=document.getElementById("extra");

    if(document.getElementById("example_button").innerText===""){
        example.style.display="none";
    }
    if(document.getElementById("extra_button").innerText===""){
        extra.style.display="none";
    }
    //音频
    const audio = document.getElementById("audio");
    function play(){audio.play();}

    //将本次卡片id存入session
    var id = JSON.parse(window.localStorage.getItem("id"));
    //若id不存在则初始化
    if(id==null){
        id=[];
    }
    id.push({{ object.id }});
    //长度不超过10
    if(id.length==11){
        id.push({{ object.id }});
        id.shift();
    }
    window.localStorage.setItem("id",JSON.stringify(id));
    //回退按钮点击事件

    function undo(){
        to = window.location.href.split('flashcards')[0]+'flashcards/undo/'+id[id.length-2];
        // 删除此次和上次的id，上次的id会自动加上
        id.pop();
        id.pop();
        window.localStorage.setItem("id",JSON.stringify(id));
        location.href=to;
    }
{% endblock %}


flashcards/templates/flashcards/list.html
<!DOCTYPE html>
<html lang="zh">
<head>

    <title>1</title></head>
<body>
<ul>

{% for card in object_list %}
    <li>{{ card.group }} - {{ card.question |safe}} - {{ card.pk }}</li>
{#{% empty %}#}
{#    <li>No articles yet.</li>#}
{% endfor %}
</ul>

</body>
</html>